name: production Build and deploy to S3
on:
  push:
    branches:
      - master_x
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: npm install, and build
      run: |
        printf "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${FA_AUTH_TOKEN}" >> ~/.npmrc
        npm ci
        npm run build
      env:
        FA_AUTH_TOKEN: ${{ secrets.FA_AUTH_TOKEN }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::922311303087:role/github-actions@dpd-zoning-summary-generator@master
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket
      working-directory: ./
      run: aws s3 sync dist s3://dpd-zoning-summary-generator --delete
